PCartWeb/Controllers/PaypalController.cs
using System;
using PayPal.Api;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Web;
using System.Web.Mvc;
using PCartWeb.Models;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Data;
using System.Configuration;
using System.Data.Entity.Spatial;
using System.Globalization;

namespace PCartWeb.Controllers
{
    public class PaypalController : Controller
    {
        // GET: Paypal
        ApplicationDbContext db = new ApplicationDbContext();
        string connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;

        public ActionResult PaymentWithPayPal(string money, string user_id, List<string> vouchcode, string Cancel = null)
        {
            Session["TotalAmount"] = money;
            //getting the apiContext  
            APIContext apiContext = PaypalConfiguration.GetAPIContext();
            try
            {
                //A resource representing a Payer that funds a payment Payment Method as paypal  
                //Payer Id will be returned when payment proceeds or click to pay  
                //A resource representing a Payer that funds a payment Payment Method as paypal
                //Payer Id will be returned when payment proceeds or click to pay
                string payerId = Request.Params["PayerId"];
                if (string.IsNullOrEmpty(payerId))
                {
                    //this section will be executed first because PayerID doesn't exist
                    //it is returned by the create function call of the payment class
                    // Creating a payment
                    // baseURL is the url on which paypal sendsback the data.
                    string baseURI = Request.Url.Scheme + "://" + Request.Url.Authority +
                    "/Paypal/PaymentWithPayPal?";
                    //here we are generating guid for storing the paymentID received in session
                    //which will be used in the payment execution
                    var guid = Convert.ToString((new Random()).Next(100000));
                    //CreatePayment function gives us the payment approval url
                    //on which payer is redirected for paypal account payment
                    var createdPayment = this.CreatePayment(apiContext, baseURI + "guid=" + guid);
                    //get links returned from paypal in response to Create function call
                    var links = createdPayment.links.GetEnumerator();
                    string paypalRedirectUrl = null;
                    while (links.MoveNext())
                    {
                        Links lnk = links.Current;
                        if (lnk.rel.ToLower().Trim().Equals("approval_url"))
                        {
                            //saving the payapalredirect URL to which user will be redirected for payment
                            paypalRedirectUrl = lnk.href;
                        }
                    }
                    // saving the paymentID in the key guid
                    Session.Add(guid, createdPayment.id);
                    return Redirect(paypalRedirectUrl);
                }
                else
                {
                    // This function exectues after receving all parameters for the payment  
                    var guid = Request.Params["guid"];
                    var executedPayment = ExecutePayment(apiContext, payerId, Session[guid] as string);
                    //If executed payment failed then we will show payment failure message to user  
                    if (executedPayment.state.ToLower() != "approved")
                    {
                        return View("FailureView");
                    }
                }
            }
            catch (Exception)
            {
                return View("FailureView");
            }
            //on successful payment, show success page to user.  

            var itemSelected = Session["Ids"].ToString();
            string[] itemsSelected = itemSelected.Split(',');
            List<string> vouchers = vouchcode;
            var db = new ApplicationDbContext();
            var user = User.Identity.GetUserId();
            var userRole = db.UserDetails.Where(u => u.AccountId == user).FirstOrDefault();
            var cart = db.Cart.Where(x => x.UserId == user).FirstOrDefault();
            var userdetails = db.UserDetails.Where(x => x.AccountId == user).FirstOrDefault();
            var dbase = new ApplicationDbContext();
            List<string> arrid = new List<string>();
            double? dist = 0;
            int final = 0;
            double? deliver_fee = 0;
            List<COOPShop> coop2 = new List<COOPShop>();
            List<UserDetails2> user2 = new List<UserDetails2>();
            List<ProductToCheckout> prodDetails = new List<ProductToCheckout>();
            List<string> IDCoop = new List<string>();
            //decimal finaltot = decimal.Parse(money);
            var userOrderId = "";
            var comRate = db.CommissionDetails.OrderByDescending(cr => cr.Id).FirstOrDefault();
            decimal subTotal = 0;
            var date = "";
            IDCoop.Clear();
            foreach (string item in itemsSelected)
            {
                List<string> coopID = new List<string>();
                var prodcart = db.ProdCart.Where(x => x.Id.ToString() == item && x.CartId == cart.Id.ToString()).FirstOrDefault();
                var prode = db.ProductDetails.Where(x => x.Id.ToString() == prodcart.ProductId).FirstOrDefault();
                PriceTable getprice = new PriceTable();
                if (prodcart.VarId == 0 || prodcart.VarId.ToString() == null)
                {
                    getprice = db.Prices.Where(x => x.ProdId.ToString() == prodcart.ProductId && (x.VarId.ToString() == null || x.VarId == 0)).OrderByDescending(p => p.Id).FirstOrDefault();
                }
                else
                {
                    getprice = db.Prices.Where(x => x.ProdId.ToString() == prodcart.ProductId && x.VarId == prodcart.VarId).FirstOrDefault();
                    if (getprice == null)
                    {
                        getprice = db.Prices.Where(x => x.ProdId.ToString() == prodcart.ProductId && (x.VarId.ToString() == null || x.VarId == 0)).OrderByDescending(p => p.Id).FirstOrDefault();
                    }
                }
                decimal memPrice = 0;
                decimal itemPrice = 0;

                if (prode.CoopId.ToString() == userRole.CoopId)
                {
                    if (userRole.Role == "Member")
                    {
                        var memDiscount = db.CoopMemberDiscounts.Where(d => d.COOP_ID.ToString() == userRole.CoopId).OrderByDescending(d => d.ID).FirstOrDefault();

                        if (memDiscount != null)
                        {
                            decimal memDisc = memDiscount.MemberDiscount;
                            decimal totDisc = getprice.Price * (memDisc / 100);
                            memPrice = getprice.Price - totDisc;
                            memPrice = decimal.Round(memPrice, 2, MidpointRounding.AwayFromZero);
                        }
                    }
                }

                var discountCheck = db.DiscountModels.ToList();

                foreach (var disCheck in discountCheck)
                {
                    CultureInfo culture = new CultureInfo("es-ES");
                    var dateStart = Convert.ToDateTime(disCheck.DateStart, culture);
                    var dateEnd = Convert.ToDateTime(disCheck.DateEnd, culture);
                    if (DateTime.Now.Ticks >= dateStart.Ticks && DateTime.Now.Ticks < dateEnd.Ticks)
                    {
                        var discountProdCheck = db.DiscountedProducts.Where(x => x.DiscountID == disCheck.Id && x.ProductId.ToString() == prodcart.ProductId).FirstOrDefault();

                        if (discountProdCheck != null)
                        {
                            if (prode.CoopId.ToString() == userRole.CoopId)
                            {
                                if (userRole.Role == "Member")
                                {
                                    var memDiscount = db.CoopMemberDiscounts.Where(d => d.COOP_ID.ToString() == userRole.CoopId).OrderByDescending(d => d.ID).FirstOrDefault();

                                    if (memDiscount != null)
                                    {
                                        decimal memDisc = memDiscount.MemberDiscount + Convert.ToDecimal(disCheck.Percent);
                                        decimal totDisc = getprice.Price * (memDisc / 100);
                                        memPrice = getprice.Price - totDisc;
                                        itemPrice = decimal.Round(memPrice, 2, MidpointRounding.AwayFromZero);
                                    }
                                    else
                                    {
                                        decimal discountPrice = getprice.Price * (Convert.ToDecimal(disCheck.Percent) / 100);
                                        decimal prodPrice = getprice.Price - discountPrice;
                                        itemPrice = decimal.Round(prodPrice, 2, MidpointRounding.AwayFromZero);
                                    }
                                }
                            }
                            else
                            {
                                decimal discountPrice = getprice.Price * (Convert.ToDecimal(disCheck.Percent) / 100);
                                decimal prodPrice = getprice.Price - discountPrice;
                                itemPrice = decimal.Round(prodPrice, 2, MidpointRounding.AwayFromZero);
                            }
                        }
                    }
                }

PCartWeb/Views/Admin/AdminComplaint.cshtml
@{
    ViewBag.Title = "AdminComplaint";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AdminComplaint</h2>
<head>
    <link rel="stylesheet" href="~/Content/css/customStyle.css">
    <style type="text/css">
        th {
            color: white;
        }
    </style>
</head>

<body>
    <div class="container-sm">
        <div class="float-right my-3 mr-3">
            <button type="submit" class="btn btn-danger">Pending</button>
            <button type="submit" class="btn btn-success">Case Closed</button>
        </div>

        <!--After Creation of Complaints, generate ticket/case number-->
        <table class="table table-hover" aria-label="Complaints">
            <thead class="bg-dark">
                <tr>
                    <th scope="col"><input type="checkbox" id="selectAll" name="selectAll"></th>
                    <th scope="col">Ticket Number</th>
                    <th scope="col">Email</th>
                    <th scope="col">Name</th>
                    <th scope="col">Reason for Complaint</th>
                    <th scope="col">Details</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row"><input type="checkbox" id="check-1" name="check-1"></th>
                    <td>T126283623523</td>
                    <td>mark@gmail.com</td>
                    <td>Mark Aragones</td>
                    <td>Cannot send payment thru system</td>
                    <td>For some reason when i clicked this button, it would not prompt me to chuchuchu</td>
                    <td>Pending</td>
                </tr>
                <tr>
                    <th scope="row"><input type="checkbox" id="check-2" name="check-2"></th>
                    <td>T126283623523</td>
                    <td>mark@gmail.com</td>
                    <td>Mark Aragones</td>
                    <td>Cannot send payment thru system</td>
                    <td>For some reason when i clicked this button, it would not prompt me to chuchuchu</td>
                    <td>Case Closed</td>
                </tr>
                <tr>
                    <th scope="row"><input type="checkbox" id="check-3" name="check-3"></th>
                    <td>T126283623523</td>
                    <td>mark@gmail.com</td>
                    <td>Mark Aragones</td>
                    <td>Cannot send payment thru system</td>
                    <td>For some reason when i clicked this button, it would not prompt me to chuchuchu</td>
                    <td>Pending</td>
                </tr>
            </tbody>
        </table>
    </div>
</body>

PCartWeb/Views/Admin/CreateCommissionRate.cshtml
@model PCartWeb.Models.CommissionTable

@{
    ViewBag.Title = "Add Commission Rate";
}

<head>
    <link rel="stylesheet" href="~/Content/css/customStyle.css" />
    <style>
        h4 {
            color: white;
        }
    </style>
</head>
<div class="container custom-form-1 custom-container">
    <div class="form-horizontal">
        <h4 class="w-100 bg-dark py-3 text-center">Commision Rate</h4>
        <hr />
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-6 mx-auto">
                    <div class="card ">
                        <div class="card-header">
                            @using (Html.BeginForm("CreateCommissionRate", "Admin", FormMethod.Post, new { enctype = "multipart/form-data", id = "form1" }))
                            {
                                @Html.AntiForgeryToken()
                                <h3>Add Commission Rate</h3>
                                <div class="tab-content">
                                    <div class="tab-pane fade show active pt-3">
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        <form role="form">
                                            <div class="form-group">
                                                @Html.EditorFor(model => model.Rate, new { htmlAttributes = new { placeholder = "Rate", @class = "form-control", type = "number", min = 1, max = 100 } })
                                                @Html.ValidationMessageFor(model => model.Rate, "", new { @class = "text-danger" })
                                                <p class="text-danger" id="ErrorRate" style="display: none;"></p>
                                            </div>
                                            <input type="submit" value="Save" class="btn btn-primary btn-block shadow-sm" />
                                        </form>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
        <script>
            $(document).ready(function () {
                $.getJSON("../Admin/LoadComRate",
                    function (data) {
                        var tr;

                        for (var i = 0; i < data.length; i++) {
                            tr = $('<tr/>');
                            tr.append("<td>" + data[i].date + "</td>");
                            tr.append("<td>" + data[i].comRate + "</td>");
                            $('.table').append(tr);
                        }

                        $('#comRateTable').DataTable({ order: [] });
                    }
                );
            });

        </script>

        <table id="comRateTable" class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Rate</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#form1').submit(function (e) {
            e.preventDefault();
            var _this = $(this);
            var rate = $("#Rate").val();

            if (rate == 0) {
                document.getElementById("ErrorRate").style.display = "block";
                document.getElementById("ErrorRate").innerHTML = "This field is required. Kindly input a valid rate.";
            }
            else {
                _this.unbind('submit').submit();
            }
        });
    });
</script>

PCartWeb/Views/Admin/EwalletHistoryDetails.cshtml
@model PCartWeb.Models.EWalletHistory

@{
    ViewBag.Title = "EwalletHistoryDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>E-Wallet History Details</h2>

<div>
    <h4>EWalletHistory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            EWallet ID
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EWallet_ID)
        </dd>

        <dt>
            Action
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Action)
        </dd>

        <dt>
            Description
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            Amount
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created_At)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

PCartWeb/Views/Admin/Index.cshtml
@using PCartWeb.Models
@model dynamic
@{
    ViewBag.Title = "Index";
    decimal ewallet = 0;
    var coop = "";
    var comm = "";
    CommissionTable commission = new CommissionTable();
    foreach(SuperAdmin ad in Model.Superadmin)
    {
        ewallet = ad.Ewallet;
        coop = ad.Cooperatives;
        comm = ad.Commission;
    }
}

<head>
    <link rel="stylesheet" href="~/Content/css/customStyle.css">
</head>
@if(ViewBag.Message != null)
{
    <script>
        window.onload = function () {
            alert("@ViewBag.Message");
        };
    </script>
}
<div class="container-fluid">
    <h2 style="margin: 25px 0 25px 0;">Dashboard</h2>

    <div class="container-fluid" style="padding: 20px; margin: 20px 0 30px 0; border: solid 10px steelblue; border-radius: 5px;">
        <div class="row gx-5">
            <div class="col px-md-4">
                <h4>Pcart E-Wallet</h4>
            </div>
        </div>
        <div class="row">
            <div class="col px-md-5">
                Amount: <b>₱ <a>@ewallet</a></b>
            </div>
            <div class="col-md-4">
                <b><a href="#"><img src="~/Images/withdraw.png" name="withdraw icon" width="32" alt="withdraw icon" />&nbsp;&nbsp;Withdraw</a></b>
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col px-md-4">
                <b>Status:</b>
            </div>
        </div>
        <div class="row">
            <div class="col px-md-5">
                Cooperatives: @coop
            </div>
        </div>
        <div class="row">
            <div class="col px-md-5">
                Current Commission Rate: @comm %
            </div>
        </div>
    </div>

    <hr />
</div>

PCartWeb/Views/Admin/ListOfCoops.cshtml
@model IEnumerable<PCartWeb.Models.CoopDetailsModel>

@{
    ViewBag.Title = "ListOfCoops";
}

<h4>List of Coops</h4>
<hr />

<head>
    <link href="~/Content/css/customStyle.css" rel="stylesheet" />
    <style>
        th {
            color: white;
        }
    </style>
</head>

<div class="table-responsive table-hover">
    <table class="table">
        <tr class="bg-dark">
            <th>
                @Html.DisplayNameFor(model => model.CoopName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contact)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Coop_Created)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Coop_Updated)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CoopName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Contact)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Coop_Created)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Coop_Updated)
                </td>
                <td>
                    @Html.ActionLink("Details", "DisplayCoopDetailReq", new { id = item.Id }) |
                    @if (item.IsLocked == "Unlock")
                    {
                        @Html.ActionLink("Lock", "LockCoop", new { id = item.Id })
                    }
                    else
                    {
                        @Html.ActionLink("Unlock", "UnlockCoop", new { id = item.Id })
                    }
                </td>
            </tr>
        }

    </table>
</div>

PCartWeb/Views/Admin/ViewCommissionSale.cshtml
@model PCartWeb.Models.ViewSalesReport

@{
    ViewBag.Title = "ViewCommissionSales";
}

<head>
    <link href="~/Content/css/customStyle.css" rel="stylesheet" />
    <style>
        th {
            color: white;
        }
    </style>
</head>

@using (Html.BeginForm())
{
    <div class="custom-form-1 custom-container w-100 col-4">
        <h4>Commission Sales</h4>
        <hr />
        <div class="form-group">
            <p>View By: </p>
            <input type="radio" id="week" name="ViewBy" value="Weekly">
            <label for="week">Weekly</label>
            <br>
            <input type="radio" id="month" name="ViewBy" value="Monthly">
            <label for="month">Monthly</label>
            <br>
            <input type="radio" id="year" name="ViewBy" value="Yearly">
            <label for="year">Yearly</label>
            <br /> <br />
            <input name="submit" type="submit" id="submit" value="Apply" class="btn btn-default" />
        </div>
    </div>
}


@*<button class="btn btn-primary" onclick="location.href = '@Url.Action("ViewCoopSales", "Paypal", new { money = totEach, user_id = id, vouchcode = vouchcode })'">Pay Order with PayPal</button>*@

@*@Html.ActionLink("Export to PDF", "Reports", new { ReportType = "PDF" }) |
    @Html.ActionLink("Export to Excel", "Reports", new { ReportType = "Excel" }) |
    @Html.ActionLink("Export to Word", "Reports", new { ReportType = "Word" })*@

@if (Model.SalesReports != null)
{
    <div class="table-responsive table-hover">
        <table class="table">
            <tr class="bg-dark">
                <th>
                    Order No.
                </th>
                <th>
                    COOP Name
                </th>
                <th>
                    Customer Name
                </th>
                <th>
                    Address
                </th>
                <th>
                    Total Amount
                </th>
                <th>
                    Commision Fee
                </th>
                <th>
                    Delivery Fee
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.SalesReports)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderNo)
                    </td>
                    <th>
                        @Html.DisplayFor(modelItem => item.CoopName)
                    </th>
                    <td>
                        @Html.DisplayFor(modelItem => item.CustomerName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalAmount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CommisionFee)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Delivery_fee)
                    </td>
                </tr>
            }
        </table>
    </div>
}

@if (Model.ViewBySales != null)
{
    <div class="table-responsive table-hover">
        <table class="table">
            <tr class="bg-dark">
                <th>
                    COOP Name
                </th>
                <th>
                    Date
                </th>
                <th>
                    Total Commissions
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.ViewBySales)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CoopName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalPrice)
                    </td>
                </tr>
            }
        </table>
    </div>
        }

PCartWeb/Views/Admin/ViewCoopSales.cshtml
@model PCartWeb.Models.ViewSalesReport

@{
    ViewBag.Title = "ViewCoopSales";
}

<head>
    <link href="~/Content/css/customStyle.css" rel="stylesheet" />
    <style>
        th {
            color: white;
        }
    </style>
</head>

@using (Html.BeginForm())
{
    <div class="custom-form-1 custom-container w-100 col-4">
        <h4>Coop Sales</h4>
        <hr />
        <div class="form-group">
            <input list="coopList" name="CoopSearch" id="CoopSearch" placeholder="Search COOP'" size="30">
            <datalist id="coopList">
                @foreach (var coop in Model.Coops)
                {
                    <option data-customvalue="@coop.CoopId" value="@coop.CoopName" />
                }
            </datalist>
        </div>
        @*<div class="form-group">
                @Html.LabelFor(model => model.CoopSearch, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.DropDownListFor(vm => vm.CoopSearch, new SelectList(Model.Coops, "CoopId", "CoopName"), "Select a COOP", htmlAttributes: new { @class = "form-control" })
                </div>
                <div class="text-danger">
                    @Model.CoopSearchError
                </div>
            </div>*@
    <div class="form-group">
        <p>View By: </p>
        <input type="radio" id="week" name="ViewBy" value="Weekly">
        <label for="week">Weekly</label>
        <br>
        <input type="radio" id="month" name="ViewBy" value="Monthly">
        <label for="month">Monthly</label>
        <br>
        <input type="radio" id="year" name="ViewBy" value="Yearly">
        <label for="year">Yearly</label>
        <br /> <br />
        <input name="submit" type="submit" id="submit" value="Apply" class="btn btn-default" />
    </div>
    </div>
}


@*<button class="btn btn-primary" onclick="location.href = '@Url.Action("ViewCoopSales", "Paypal", new { money = totEach, user_id = id, vouchcode = vouchcode })'">Pay Order with PayPal</button>*@

@*@Html.ActionLink("Export to PDF", "Reports", new { ReportType = "PDF" }) |
    @Html.ActionLink("Export to Excel", "Reports", new { ReportType = "Excel" }) |
    @Html.ActionLink("Export to Word", "Reports", new { ReportType = "Word" })*@


@if (Model.SalesReports != null)
{
    <div class="table-responsive table-hover">
        <table class="table">
            <tr class="bg-dark">
                <th>
                    Order No.
                </th>
                <th>
                    COOP Name
                </th>
                <th>
                    Customer Name
                </th>
                <th>
                    Address
                </th>
                <th>
                    Total Amount
                </th>
                <th>
                    Commision Fee
                </th>
                <th>
                    Delivery Fee
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.SalesReports)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderNo)
                    </td>
                    <th>
                        @Html.DisplayFor(modelItem => item.CoopName)
                    </th>
                    <td>
                        @Html.DisplayFor(modelItem => item.CustomerName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalAmount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CommisionFee)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Delivery_fee)
                    </td>
                </tr>
            }
        </table>
    </div>
}

@if (Model.ViewBySales != null)
{
    <div class="table-responsive table-hover">
        <table class="table">
            <tr class="bg-dark">
                <th>
                    COOP Name
                </th>
                <th>
                    Date
                </th>
                <th>
                    Total Price
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.ViewBySales)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CoopName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalPrice)
                    </td>
                </tr>
            }
        </table>
    </div>
        }