PCartWeb/Controllers/CoopadminController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using PCartWeb.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Spatial;
using System.Data.SqlClient;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mime;
using System.Security.Cryptography;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Globalization;
using PCartWeb.Hubs;

namespace PCartWeb.Controllers
{
    [Authorize(Roles = "Coop Admin")]
    public class CoopadminController : Controller
    {
        // GET: Coopadmin

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        string connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        public ActionResult Index()
        {
            var db = new ApplicationDbContext();
            var user = User.Identity.GetUserId();

            List<UserViewModel> userview = new List<UserViewModel>();
            List<ProductDetailsModel> product = new List<ProductDetailsModel>();
            List<PriceTable> price = new List<PriceTable>();
            List<ProductManufacturer> manufacturer = new List<ProductManufacturer>();
            List<int> productID = new List<int>();

            var coopAdmin = db.CoopAdminDetails.Where(x => x.UserId == user).FirstOrDefault();
            var coop = db.CoopDetails.Where(x => x.Id == coopAdmin.Coop_code).FirstOrDefault();
            var productDetails = db.ProductDetails.Where(x => x.CoopId == coop.Id && x.Product_status == "Approved" && x.Product_qty != 0).ToList();
            var member = db.UserDetails.Where(x => x.CoopId == user).ToList();
            var commission = db.CommissionDetails.FirstOrDefault();
            var discountCheck = db.DiscountModels.Where(x => x.CoopID == coop.Id).ToList();
            var userOrder = db.UserOrders.Where(x => x.CoopId == coop.Id && x.OStatus == "Complete").ToList();

            foreach (var order in userOrder)
            {
                var deliveryStatus = db.DeliverStatus.Where(x => x.UserOrderId == order.Id).FirstOrDefault();
                var dateDelivered = Convert.ToDateTime(deliveryStatus.DateDelivered);

                if (dateDelivered.AddDays(7) <= DateTime.Now)
                {
                    var coopEwallet = db.UserEWallet.Where(x => x.COOP_ID == order.CoopId.ToString() && x.Status == "Active").FirstOrDefault();
                    coopEwallet.Balance += ((order.TotalPrice + Convert.ToDecimal(order.Delivery_fee)) - order.CommissionFee);
                    db.Entry(coopEwallet).State = EntityState.Modified;
                    db.SaveChanges();

                    var ewalletHistory = new EWalletHistory();
                    ewalletHistory.EWallet_ID = coopEwallet.ID;
                    ewalletHistory.Amount = ((order.TotalPrice + Convert.ToDecimal(order.Delivery_fee)) - order.CommissionFee);
                    ewalletHistory.Action = "Order Payment";
                    ewalletHistory.Description = "Payment received from Order No. " + order.Id + ".";
                    ewalletHistory.Created_At = DateTime.Now;
                    db.EWalletHistories.Add(ewalletHistory);
                    db.SaveChanges();

                    var admin = db.Users.Where(x => x.Email == "PCartTeam@gmail.com").FirstOrDefault();
                    var adminEwallet = db.UserEWallet.Where(x => x.UserID == admin.Id).FirstOrDefault();
                    adminEwallet.Balance -= ((order.TotalPrice + Convert.ToDecimal(order.Delivery_fee)) - order.CommissionFee);
                    db.Entry(adminEwallet).State = EntityState.Modified;
                    db.SaveChanges();

                    var coopDetails = db.CoopDetails.Where(x => x.Id.ToString() == coopEwallet.COOP_ID).FirstOrDefault();
                    ewalletHistory = new EWalletHistory();
                    ewalletHistory.EWallet_ID = adminEwallet.ID;
                    ewalletHistory.Amount = ((order.TotalPrice + Convert.ToDecimal(order.Delivery_fee)) - order.CommissionFee);
                    ewalletHistory.Action = "Payment Send";
                    ewalletHistory.Description = "Payment from Order No. " + order.Id + " is sent to " + coopDetails.CoopName + "(" + coopDetails.Id + ").";
                    ewalletHistory.Created_At = DateTime.Now;
                    db.EWalletHistories.Add(ewalletHistory);
                    db.SaveChanges();

                    order.OStatus = "Transfered";
                    db.Entry(order).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }

            foreach (var disCheck in discountCheck)
            {
                CultureInfo culture = new CultureInfo("es-ES");
                var dateStart = Convert.ToDateTime(disCheck.DateStart, culture);
                var dateEnd = Convert.ToDateTime(disCheck.DateEnd, culture);
                if (DateTime.Now.Ticks >= dateStart.Ticks && DateTime.Now.Ticks < dateEnd.Ticks)
                {
                    foreach (var item in productDetails)
                    {
                        var getprice = db.Prices.Where(x => x.ProdId == item.Id && (x.VarId.ToString() == null || x.VarId == 0)).OrderByDescending(p => p.Id).FirstOrDefault();
                        var getmanu = db.Manufacturer.Where(x => x.ProdId == item.Id).OrderByDescending(p => p.Id).FirstOrDefault();
                        var discountProdCheck = db.DiscountedProducts.Where(x => x.DiscountID == disCheck.Id && x.ProductId == item.Id).FirstOrDefault();

                        if (discountProdCheck != null)
                        {
                            decimal discountPrice = getprice.Price * (Convert.ToDecimal(disCheck.Percent) / 100);
                            decimal prodPrice = getprice.Price - discountPrice;

                            product.Add(new ProductDetailsModel
                            {
                                Product_image = item.Product_image,
                                Id = item.Id,
                                Product_desc = item.Product_desc,
                                Product_Name = item.Product_Name,
                                DiscountedPrice = decimal.Round(prodPrice, 2, MidpointRounding.AwayFromZero),
                                Product_qty = item.Product_qty,
                                Categoryname = item.Categoryname,
                                Category_Id = item.Category_Id
                            });

                            price.Add(new PriceTable
                            {
                                ProdId = item.Id,
                                Price = getprice.Price
                            });

                            manufacturer.Add(new ProductManufacturer
                            {
                                ProdId = item.Id,
                                Manufacturer = getmanu.Manufacturer
                            });

                            productID.Add(item.Id);
                        }
                    }
                }
            }

            foreach (var item in productDetails)
            {
                if (!productID.Contains(item.Id))
                {
                    var getprice = db.Prices.Where(x => x.ProdId == item.Id && (x.VarId.ToString() == null || x.VarId == 0)).OrderByDescending(p => p.Id).FirstOrDefault();
                    var getmanu = db.Manufacturer.Where(x => x.ProdId == item.Id).OrderByDescending(p => p.Id).FirstOrDefault();

                    product.Add(new ProductDetailsModel
                    {
                        Product_image = item.Product_image,
                        Id = item.Id,
                        Product_desc = item.Product_desc,
                        Product_Name = item.Product_Name,
                        Product_qty = item.Product_qty,
                        Categoryname = item.Categoryname,
                        Category_Id = item.Category_Id
                    });

                    price.Add(new PriceTable
                    {
                        ProdId = item.Id,
                        Price = getprice.Price
                    });

                    manufacturer.Add(new ProductManufacturer
                    {
                        ProdId = item.Id,
                        Manufacturer = getmanu.Manufacturer
                    });
                }
            }

            productID.Clear();

            if (commission == null)
            {
                var ewallet = db.UserEWallet.Where(x => x.UserID == user && x.Status == "Active").FirstOrDefault();
                userview.Add(new UserViewModel
                {
                    Firstname = coop.CoopName,

PCartWeb/Views/Coopadmin/AccountPayables.cshtml
@model PCartWeb.Models.AccountPayablesRepModel

@{
    ViewBag.Title = "AccountPayables";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <link href="~/Content/css/customStyle.css" rel="stylesheet" />
    <style>
        th {
            color: white;
        }
    </style>
</head>
<h2>Account Payables</h2>
<div class="custom-form-1 custom-container w-100 col-4">
    <h4>Accounts Payable</h4>
    <hr />
    <div class="form-group">
        <p style="color:red;">@ViewBag.ErrorMessage</p>
        @if (Model.IsSucess == true)
        {
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                You have successfully paid your fees. Thank you
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }
        @if (Model.Status != null)
        {
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                @Model.Status <br />
                @Model.DueDate <br />
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        }

        <input class="form-control" disabled type="text" value="Total: PHP @Model.TotalTobePay" />
        <br />
        <input name="submit" type="submit" id="submit" data-toggle="modal" data-target="#exampleModal2" value="Mark as Done" class="btn btn-default" />
    </div>
</div>
@if (Model.CommissionSale != null)
{
    <div class="table-responsive table-hover">
        <table class="table">
            <tr class="bg-dark">
                <th>
                    Order No.
                </th>
                <th>
                    Commission Fee
                </th>
                <th>
                    Status
                </th>
                <th>
                    Date Created
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.CommissionSale)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserOrderID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CommissionFee)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Created_at)
                    </td>
                </tr>
            }
        </table>
    </div>
}

@using (Html.BeginForm("AccountPayables", "Coopadmin", FormMethod.Post, new { enctype = "multipart/form-data", id = "form1" }))
{
    <div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Account Resignation</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="file" name="ReceiptFile" class="form-control" />
                </div>
                <div class="modal-body">
                    <input type="radio" id="paypal" name="Mode" checked value="Paypal">
                    <label for="paypal">Paypal</label>
                    <br>
                    <input type="radio" id="mlhuillier" name="Mode" checked value="MLhuillier">
                    <label for="mlhuillier">MLhuillier</label>
                    <br>
                    <input type="radio" id="cebuana" name="Mode" value="Cebuana">
                    <label for="cebuana">Cebuana</label>
                    <br>
                    <input type="radio" id="palawan" name="Mode" value="Palawan"/>
                    <label for="palawan">Palawan</label>
                </div>
                <div class="modal-body">
                    @Html.EditorFor(model => Model.Email, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="modal-body">
                    @Html.EditorFor(model => Model.Fullname, new { htmlAttributes = new { @class = "form-control" } })
                    
                </div>
                <div class="modal-body">
                    @Html.EditorFor(model => Model.Contact, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="modal-body">
                    @Html.HiddenFor(model => Model.TotalTobePay)
                    <p>The total amount to be payed is PHP @Model.TotalTobePay. Would you like to proceed?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input type="submit" name="submit" value="Proceed" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
}

PCartWeb/Views/Coopadmin/CreateMember.cshtml
@model PCartWeb.Models.RegisterViewModel

@{
    ViewBag.Title = "CreateMember";
}

<head>
    <link rel="stylesheet" href="~/Content/css/customStyle.css" />
    <style>
        .form-group {
            margin-bottom: 0.3rem;
        }

        h4 {
            color: white;
        }
    </style>
</head>

<p style="color:red;">@ViewBag.Errormessage</p>

<div class="custom-form-1 mt-5 w-75 mx-md-auto">
    @using (Html.BeginForm("CreateMember", "Coopadmin", FormMethod.Post, new { enctype = "multipart/form-data", id = "form1" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal ml-md-3">
            <h4 class="w-100 bg-dark py-3 text-center">Register Member</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-10">
                    <input type="file" name="ImageFile" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Contact, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Bdate, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-10">
                    <input type="date" id="Bdate" name="Bdate" class="form-control" placeholder="dd/mm/yyyy" />
                    <p class="text-danger" style="visibility: hidden" id="ErrorBDate"></p>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-10">
                    @Html.DropDownListFor(vm => vm.Gender, Model.GenderList, "-Please Select-", htmlAttributes: new { @class = "form-control" })
                    <p class="text-danger">@ViewBag.GenderError</p>
                </div>
            </div>
            @Html.HiddenFor(model => model.Password, new { @Value = "@1234Abcd" })

            @Html.HiddenFor(model => model.ConfirmPassword, new { @Value = "@1234Abcd" })
            <div class="form-group">
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>

    <div>
        @Html.ActionLink("Back to List", "ViewMemberList")
    </div>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyCCnmMReV03W96lvqJVwbG7nFOTkuUDaX8"></script>
    <script type="text/javascript">
        google.maps.event.addDomListener(window, 'load', function () {
            var options = {
                componentRestrictions: { country: "ph" }
            };

            var input = document.getElementById('Address');
            var places = new google.maps.places.Autocomplete(input, options);
            google.maps.event.addListener(places, 'place_changed', function () {
                var place = places.getPlace();
                $("#Longitude").val("" + place.geometry.location.lng());
                $("#Latitude").val("" + place.geometry.location.lat());
            });

        });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            flatpickr("#Bdate", {
                dateFormat: 'j/n/Y',
                minDate: "1/1/1905",
                maxDate: "today"
            });

            $('#form1').submit(function (e) {
                e.preventDefault();
                var _this = $(this);
                var bdate = $("#Bdate").val();
                var date = bdate.split('/');
                var currDate = new Date();
                var year = currDate.getFullYear() - 18;

                if (bdate == "") {
                    document.getElementById('ErrorBDate').style.visibility = "visible";
                    document.getElementById("ErrorBDate").innerHTML = "This field is required. Kindly iput your birthdate.";
                }
                else if (date[2] > year) {
                    document.getElementById('ErrorBDate').style.visibility = "visible";
                    document.getElementById("ErrorBDate").innerHTML = "You must be 18 to register.";
                }
                else {
                    _this.unbind('submit').submit();
                }
            });
        });
    </script>

PCartWeb/Views/Coopadmin/EditProductImage.cshtml
@model PCartWeb.Models.ExternalImages

@{
    ViewBag.Title = "EditProductImage";
}

<head>
    <link href="~/Content/css/customStyle.css" rel="stylesheet" />
    <style>
        h4 {
            color: white;
        }
    </style>
</head>

@using (Html.BeginForm("EditProductImage", "Coopadmin", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="container form-horizontal custom-form-1 custom-container w-75">
        <h4 class="w-100 bg-dark py-3 text-center">Edit Product Image</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Product_image, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-10">
                <input class="form-control" name="ImageFile" type="file" id="formFile">
                @Html.ValidationMessageFor(model => model.Product_image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-default" />
            </div>
        </div>
    </div>
}

PCartWeb/Views/Coopadmin/ProdDetails.cshtml
@model PCartWeb.Models.EditProductModel

@{
    ViewBag.Title = "ProdDetails";
}

<head>
    <style>
        body {
            margin-top: 20px;
        }

        .panel.panel-default {
            border-top-width: 3px;
        }

        .panel {
            border: 0;
            border-radius: 4px;
            margin-bottom: 16px;
        }

        .thumb96 {
            width: 500px !important;
            height: 500px !important;
        }

        .thumb48 {
            width: 48px !important;
            height: 48px !important;
        }

        .center {
            margin-left: 10%;
        }
    </style>
</head>

<div class="container center mt-5">
    <div class="container bootstrap snippets bootdey">
        <div class="row ng-scope">
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-body text-center">
                        <div class="pv-lg">
                            <img src="@Url.Content("~/Images/"+Model.ProductDetailsModel.Product_image)" width="320" height="320" />
                        </div>
                    </div>
                </div>
                <div class="panel panel-default hidden-xs hidden-sm" style="padding: 20px; box-shadow: 0 5px 8px 0 rgba(0, 0, 0, 0.2), 0 9px 26px 0 rgba(0, 0, 0, 0.19);">
                    <div class="form-group">
                        <label class="col-sm-5 control-label" for="inputContact8">Date Created</label>
                        <div class="col-sm-11">
                            <input class="form-control" id="inputContact8" type="text" value="@Model.ProductDetailsModel.Prod_Created_at" disabled />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label" for="inputContact8">Date Updated</label>
                        <div class="col-sm-11">
                            <input class="form-control" id="inputContact8" type="text" value="@Model.ProductDetailsModel.Prod_Updated_at" disabled>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6" style="padding: 40px; box-shadow: 0 5px 8px 0 rgba(0, 0, 0, 0.2), 0 9px 26px 0 rgba(0, 0, 0, 0.19); margin-bottom: 20px;">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="h4 text-center">Product Details</div>
                        <div class="row">
                            <div class="col">
                                <form class="form-horizontal">
                                    <div class="form-group">
                                        <label class="h6 col-sm-2 control-label" for="inputContact1">Name</label>
                                        <div class="col-sm-12">
                                            <input class="form-control" id="inputContact3" type="text" value="@Model.ProductDetailsModel.Product_Name" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="h6 col-sm-2 control-label" for="inputContact2">Description</label>
                                        <div class="col-sm-12">
                                            <textarea class="form-control" rows="5" id="comment" placeholder="@Model.ProductDetailsModel.Product_desc" disabled></textarea>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputContact3">Manufacturer</label>
                                        <div class="col-sm-12">
                                            <input class="form-control" id="inputContact3" type="text" value="@Model.ProductManufacturer.Manufacturer" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputContact4">Qty</label>
                                        <div class="col-sm-12">
                                            <input class="form-control" id="inputContact4" type="text" value="@Model.ProductDetailsModel.Product_qty" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputContact5">Cost</label>
                                        <div class="col-sm-12">
                                            <input class="form-control" id="inputContact5" type="text" value="@Model.ProductCost.Cost" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputContact6">Price</label>
                                        <div class="col-sm-12">
                                            <input class="form-control" id="inputContact5" type="text" value="@Model.PriceTable.Price" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label" for="inputContact7">Category</label>
                                        <div class="col-sm-12">
                                            <input class="form-control" id="inputContact7" type="text" value="@Model.ProductDetailsModel.Categoryname" disabled>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary" onclick="location.href = '@Url.Action("EditProduct", "Coopadmin", new { id = Model.ProductDetailsModel.Id })'">Edit</button>
                <button class="btn btn-primary" onclick="location.href = '@Url.Action("ViewListProduct", "Coopadmin", new { id = Model.ProductDetailsModel.Id })'">Back</button>
            </div>
        </div>
    </div>
</div>
@*<p>
    @Html.ActionLink("Edit", "EditProduct", new { id = Model.ProductDetailsModel.Id }) |
    @Html.ActionLink("Back to List", "ViewListProduct")
</p>*@